/* Story Time: short moral / inspirational tales for a 5-year-old.
   Each story has 8-10 "scenes" (the last scene is the moral).
   Big emoji art + one or two simple sentences, read aloud. */
window.STORIES = [
  {
    id: 'crow',
    title: 'The Thirsty Crow',
    cover: '🐦‍⬛',
    scenes: [
      { art: '🐦‍⬛☀️', text: 'On a hot, sunny day, a little crow was very, very thirsty.' },
      { art: '🔍🌳', text: 'She flew here and there, looking everywhere for water.' },
      { art: '🏺', text: 'At last she found a tall pot with a little water at the bottom.' },
      { art: '🐦‍⬛🏺', text: 'But the water was too low. She could not reach it!' },
      { art: '🤔💡', text: 'The clever crow thought and thought... then she had an idea!' },
      { art: '🪨🪨', text: 'She picked up small stones, one by one.' },
      { art: '🏺💦', text: 'Plop! Plop! She dropped each stone into the pot.' },
      { art: '⬆️💧', text: 'Slowly, the water rose higher and higher.' },
      { art: '🐦‍⬛😋', text: 'Now she could drink. The happy crow drank every drop!' },
      { art: '🌟', text: 'Moral: Where there is a will, there is a way.' },
    ],
  },
  {
    id: 'tortoise',
    title: 'The Tortoise and the Hare',
    cover: '🐢',
    scenes: [
      { art: '🐇💨', text: 'A speedy hare loved to brag, "I am the fastest of all!"' },
      { art: '🐢🙂', text: 'A slow little tortoise said, "Let us have a race."' },
      { art: '🐇😂', text: 'The hare laughed. "You? Race me? This will be easy!"' },
      { art: '🏁🏃', text: 'Ready, set, GO! The hare zoomed far, far ahead.' },
      { art: '🐇😴🌳', text: 'So far ahead that he took a nap under a tree.' },
      { art: '🐢👣', text: 'The tortoise kept walking, step by step, never stopping.' },
      { art: '🐢➡️🐇', text: 'Slowly he passed the sleeping hare.' },
      { art: '🐇😱', text: 'The hare woke up and ran, but it was too late!' },
      { art: '🐢🏆', text: 'The tortoise crossed the finish line and won!' },
      { art: '🌟', text: 'Moral: Slow and steady wins the race.' },
    ],
  },
  {
    id: 'ant',
    title: 'The Ant and the Grasshopper',
    cover: '🐜',
    scenes: [
      { art: '☀️🌻', text: 'It was a warm summer. A grasshopper played and sang all day.' },
      { art: '🐜🌾', text: 'A busy ant worked hard, carrying food to her home.' },
      { art: '🦗🎶', text: '"Come play!" said the grasshopper. "Why work so hard?"' },
      { art: '🐜❄️', text: '"Winter is coming," said the ant. "We must be ready."' },
      { art: '🦗😴', text: 'But the grasshopper just laughed and kept playing.' },
      { art: '❄️🌨️', text: 'Soon, cold winter came. The fields were covered in snow.' },
      { art: '🦗🥶', text: 'The grasshopper was hungry and cold. There was no food!' },
      { art: '🐜🏠🍲', text: 'The kind ant had a warm home and plenty to eat.' },
      { art: '🐜🤝🦗', text: 'She shared her food, and the grasshopper learned his lesson.' },
      { art: '🌟', text: 'Moral: Work hard today, and you will be ready for tomorrow.' },
    ],
  },
  {
    id: 'lion',
    title: 'The Lion and the Mouse',
    cover: '🦁',
    scenes: [
      { art: '🦁😴', text: 'A big lion was fast asleep in the warm sun.' },
      { art: '🐭🏃', text: 'A tiny mouse ran across his nose and woke him up!' },
      { art: '🦁😾', text: 'The lion grabbed the little mouse with his huge paw.' },
      { art: '🐭🙏', text: '"Please let me go," squeaked the mouse. "One day I will help you!"' },
      { art: '🦁😄', text: 'The lion laughed, "How can YOU help ME?" But he let her go.' },
      { art: '🕸️🦁', text: 'Days later, the lion got caught in a hunter’s net.' },
      { art: '🦁😢', text: 'He roared and roared, but he could not get free.' },
      { art: '🐭👂', text: 'The little mouse heard him and came running.' },
      { art: '🐭✂️', text: 'She chewed the ropes until the lion was free!' },
      { art: '🌟', text: 'Moral: Even the smallest friend can be a big help.' },
    ],
  },
  {
    id: 'seed',
    title: 'The Little Seed',
    cover: '🌱',
    scenes: [
      { art: '🌰🤲', text: 'A little girl planted one tiny seed in the soft brown soil.' },
      { art: '💧☀️', text: 'Every day she gave it water and let it feel the sun.' },
      { art: '🌱👀', text: 'For many days, nothing happened. The seed stayed hidden.' },
      { art: '😟', text: '"Will it ever grow?" she wondered. But she did not give up.' },
      { art: '🌱✨', text: 'One morning, a tiny green sprout peeked out of the soil!' },
      { art: '🌿📈', text: 'Day by day, it grew taller and stronger.' },
      { art: '🌷🌼', text: 'Soon, beautiful flowers bloomed all around.' },
      { art: '🦋🐝', text: 'Butterflies and bees came to visit the lovely garden.' },
      { art: '😊🌻', text: 'The girl smiled. Her patience had grown something wonderful.' },
      { art: '🌟', text: 'Moral: Good things grow for those who are patient and kind.' },
    ],
  },
  {
    id: 'bear',
    title: 'The Two Friends and the Bear',
    cover: '🐻',
    scenes: [
      { art: '👬🌳', text: 'Two friends were walking through a big, green forest.' },
      { art: '🐻😨', text: 'Suddenly, a big bear came out from behind the trees!' },
      { art: '🏃🌳', text: 'One friend ran fast and climbed up a tall tree.' },
      { art: '🧍😰', text: 'The other friend did not know how to climb. He was scared.' },
      { art: '💡🛌', text: 'He remembered: bears do not touch those who lie very still.' },
      { art: '🧍⬇️', text: 'So he lay down on the ground and held his breath.' },
      { art: '🐻👃', text: 'The bear sniffed his ear... then walked away.' },
      { art: '🌳👀', text: 'The friend in the tree climbed down. "What did the bear say?"' },
      { art: '🗣️🤝', text: '"He said: a true friend never leaves you in trouble."' },
      { art: '🌟', text: 'Moral: A true friend stays with you, even in hard times.' },
    ],
  },
  {
    id: 'sun',
    title: 'The Sun and the Wind',
    cover: '🌞',
    scenes: [
      { art: '🌬️🌞', text: 'The Wind and the Sun argued about who was stronger.' },
      { art: '🚶🧥', text: 'They saw a man walking, wearing a warm coat.' },
      { art: '🌬️💪', text: '"Whoever makes him take off his coat wins!" said the Wind.' },
      { art: '🌬️🥶', text: 'The Wind blew hard and cold, whoosh, whoosh!' },
      { art: '🧥🤗', text: 'But the man only held his coat tighter and tighter.' },
      { art: '🌬️😮‍💨', text: 'The Wind blew and blew until he was all tired out.' },
      { art: '🌞😊', text: 'Then the Sun came out and shone warm and gentle.' },
      { art: '☀️😅', text: 'The man felt warm... so he took off his coat!' },
      { art: '🌞🏆', text: 'The gentle Sun had won.' },
      { art: '🌟', text: 'Moral: Kindness and gentleness are stronger than force.' },
    ],
  },

  /* ---------- Bedtime stories 🌙 ---------- */
  {
    id: 'sleepystar',
    title: 'The Sleepy Little Star',
    cover: '⭐',
    scenes: [
      { art: '🌙⭐', text: 'High in the night sky lived a little star named Twinkle.' },
      { art: '⭐✨', text: 'Every night, Twinkle shone her soft, silver light.' },
      { art: '🏠😴', text: 'Her light peeked through windows to help children fall asleep.' },
      { art: '🧸💤', text: 'She watched over teddy bears and warm, cozy blankets.' },
      { art: '🌛', text: 'The gentle Moon smiled. "You do such kind work, Twinkle."' },
      { art: '🥱⭐', text: 'But soon Twinkle began to yawn. She was very sleepy too.' },
      { art: '🌅', text: 'As morning came near, the sky turned soft and pink.' },
      { art: '☁️⭐', text: 'Twinkle snuggled behind a fluffy little cloud.' },
      { art: '😌💤', text: 'She closed her twinkly eyes and drifted off to sleep.' },
      { art: '🌟', text: 'Moral: After helping others, it is our turn to rest. Sweet dreams! 🌙' },
    ],
  },
  {
    id: 'goodnightbunny',
    title: 'Goodnight, Little Bunny',
    cover: '🐰',
    scenes: [
      { art: '🐰🌙', text: 'When the moon came out, Little Bunny got ready for bed.' },
      { art: '🥕', text: 'He had one last nibble of his crunchy carrot. Munch, munch!' },
      { art: '🪥', text: 'Then he brushed his tiny teeth until they were sparkly clean.' },
      { art: '🐤', text: '"Goodnight, little bird," he whispered. The bird tucked its head.' },
      { art: '🌸', text: '"Goodnight, flowers," he said. The flowers closed their petals.' },
      { art: '🌙', text: '"Goodnight, moon," he yawned, waving a soft paw.' },
      { art: '🛏️', text: 'Little Bunny hopped into his warm, snuggly bed.' },
      { art: '🧸', text: 'He hugged his soft teddy close to his chest.' },
      { art: '😴', text: 'His eyes felt heavy... and slowly closed.' },
      { art: '🌟', text: 'Moral: A calm goodnight to everyone makes bedtime cozy. 💛' },
    ],
  },
  {
    id: 'moonblanket',
    title: 'The Moon’s Soft Blanket',
    cover: '🌙',
    scenes: [
      { art: '🌙', text: 'Every evening, the kind Moon rose high into the sky.' },
      { art: '✨', text: 'She spread her soft, glowing light over the whole world.' },
      { art: '🏙️😴', text: 'It was like a warm blanket for sleepy towns and homes.' },
      { art: '🐦🌳', text: 'Birds tucked into their nests among the leaves.' },
      { art: '🐟🌊', text: 'Little fish rested gently at the bottom of the sea.' },
      { art: '🐶🏠', text: 'Puppies curled up on their cozy beds.' },
      { art: '👶🛏️', text: 'And children snuggled under their own soft blankets.' },
      { art: '🌙💫', text: 'The Moon watched over them all, quiet and calm.' },
      { art: '🤫', text: '"Shhh," she whispered. "It is time to rest now."' },
      { art: '🌟', text: 'Moral: The night is a gentle blanket that helps us rest. 🌙' },
    ],
  },
  {
    id: 'sleepyowl',
    title: 'The Little Owl Who Wouldn’t Sleep',
    cover: '🦉',
    scenes: [
      { art: '🦉', text: 'Little Owl loved to play all through the night.' },
      { art: '🌙', text: '"I am not sleepy!" he hooted, flapping his wings.' },
      { art: '🦋', text: 'He chased moths and swooped around the big oak tree.' },
      { art: '🥱', text: 'But soon his wings felt heavy and slow.' },
      { art: '😵‍💫', text: 'His eyes began to blink... and droop... and blink.' },
      { art: '🌳', text: 'Mama Owl called softly, "Come rest, my little one."' },
      { art: '🪺', text: 'Little Owl flew home to his warm, round nest.' },
      { art: '🤗', text: 'Mama wrapped a soft, feathery wing around him.' },
      { art: '😴', text: 'At last, Little Owl closed his big eyes and slept.' },
      { art: '🌟', text: 'Moral: Even when we want to play, our body needs rest. 💤' },
    ],
  },
  {
    id: 'dreamycloud',
    title: 'The Dreamy Little Cloud',
    cover: '☁️',
    scenes: [
      { art: '☁️', text: 'Once there was a soft little cloud named Puff.' },
      { art: '🌙', text: 'Every night, Puff floated across the starry sky.' },
      { art: '💭', text: 'Puff carried happy dreams to sleeping children.' },
      { art: '🍭🎠', text: 'Dreams of candy, carousels, and playful puppies.' },
      { art: '👧😊', text: 'A little girl smiled in her sleep as a sweet dream arrived.' },
      { art: '🌈', text: 'Puff sprinkled a dream of a big rainbow slide.' },
      { art: '⭐', text: 'The stars twinkled, "Well done, little Puff!"' },
      { art: '🥱☁️', text: 'Then Puff grew sleepy from all that gentle flying.' },
      { art: '😴', text: 'He rested on the soft night breeze and dozed off.' },
      { art: '🌟', text: 'Moral: Kind thoughts make the sweetest dreams. Goodnight! 💤' },
    ],
  },
  {
    id: 'tiredtrain',
    title: 'The Tired Little Train',
    cover: '🚂',
    scenes: [
      { art: '🚂', text: 'Choo-choo! The little blue train worked hard all day.' },
      { art: '🍎', text: 'He carried baskets of apples up the tall green hills.' },
      { art: '🐮🐑', text: 'He waved at cows and sheep along the way. Toot-toot!' },
      { art: '🌆', text: 'By evening, the sky turned orange and gold.' },
      { art: '🥱', text: 'The little train felt tired. His wheels went slower and slower.' },
      { art: '🚉', text: 'At last he chugged into the quiet, cozy station.' },
      { art: '🧑‍🔧', text: 'The kind station master gave him a gentle pat.' },
      { art: '🌙', text: '"You did a wonderful job today," he said softly.' },
      { art: '😴', text: 'The little train sighed happily and fell fast asleep.' },
      { art: '🌟', text: 'Moral: After a busy day, rest is well deserved. 💤' },
    ],
  },
  {
    id: 'fireflylight',
    title: 'The Little Firefly’s Light',
    cover: '✨',
    scenes: [
      { art: '✨🌙', text: 'In the dark forest lived a tiny firefly named Glow.' },
      { art: '🌲', text: 'Her light was small, but warm and golden.' },
      { art: '🐭😟', text: 'One night, a little mouse was lost and scared in the dark.' },
      { art: '✨', text: 'Glow flew close. "Follow my light," she said kindly.' },
      { art: '🌿', text: 'She lit the path past the ferns and the old logs.' },
      { art: '🏠🐭', text: 'Soon the little mouse found his cozy home. "Thank you!"' },
      { art: '😊✨', text: 'Glow felt happy that her little light had helped.' },
      { art: '🌙', text: 'The moon smiled down on the quiet, sleepy forest.' },
      { art: '😴', text: 'Glow dimmed her light and curled up on a soft leaf.' },
      { art: '🌟', text: 'Moral: Even a small light can help someone. Goodnight! 💛' },
    ],
  },
  {
    id: 'lioncub',
    title: 'The Yawning Lion Cub',
    cover: '🦁',
    scenes: [
      { art: '🦁', text: 'Little Leo the lion cub had played all day long.' },
      { art: '☀️', text: 'He pounced on leaves and rolled in the warm grass.' },
      { art: '🌇', text: 'When the sun went down, the land grew calm and quiet.' },
      { art: '🥱', text: 'Leo let out a great big yawn. "Roooar-yawn!"' },
      { art: '🦁💛', text: 'Mama Lion licked his fluffy mane. "Time for bed, little one."' },
      { art: '🌳', text: 'They snuggled together under the big acacia tree.' },
      { art: '🌙', text: 'The stars came out, one by one, over the sleepy land.' },
      { art: '🫧', text: 'Leo listened to the soft night sounds. All was peaceful.' },
      { art: '😴', text: 'With a happy sigh, Little Leo drifted off to sleep.' },
      { art: '🌟', text: 'Moral: A cuddle from someone we love makes bedtime cozy. 💤' },
    ],
  },
  {
    id: 'sleepysunflower',
    title: 'The Sleepy Sunflower',
    cover: '🌻',
    scenes: [
      { art: '🌻☀️', text: 'In a sunny garden grew a cheerful sunflower named Sunny.' },
      { art: '☀️', text: 'All day, Sunny turned her face to follow the warm sun.' },
      { art: '🐝🦋', text: 'Bees and butterflies came by to say hello.' },
      { art: '🌇', text: 'But when evening came, the sun began to set.' },
      { art: '🌙', text: 'The sky grew dark and cool, and the stars peeked out.' },
      { art: '🌻😴', text: 'Slowly, Sunny began to droop her sleepy head.' },
      { art: '🍃', text: 'She folded her golden petals in, soft and snug.' },
      { art: '🤫', text: 'The garden was quiet. The crickets sang a gentle song.' },
      { art: '😌', text: 'Sunny rested, dreaming of tomorrow’s bright sunshine.' },
      { art: '🌟', text: 'Moral: Rest tonight, and shine bright again tomorrow. 🌙' },
    ],
  },
  {
    id: 'teddyhug',
    title: 'Teddy’s Goodnight Hug',
    cover: '🧸',
    scenes: [
      { art: '🧸', text: 'Every night, Teddy waited on the soft, comfy bed.' },
      { art: '👧', text: 'Little Mia came in, all cozy in her pajamas.' },
      { art: '🛁', text: 'She had washed up and was warm and squeaky clean.' },
      { art: '📖', text: 'Mama read one gentle story in a soft, quiet voice.' },
      { art: '🌙', text: 'Then it was time to turn off the big light.' },
      { art: '💡', text: 'Only the little nightlight glowed, warm and orange.' },
      { art: '🧸🤗', text: 'Mia hugged Teddy tight. "Goodnight, Teddy," she whispered.' },
      { art: '😴', text: 'Teddy felt her breathing grow slow and soft.' },
      { art: '💤', text: 'Together, they drifted into happy, peaceful dreams.' },
      { art: '🌟', text: 'Moral: A hug and a story make the sweetest goodnight. 💛' },
    ],
  },
];
