/* Story Time: short moral / inspirational tales for a 5-year-old.
   Each story has 8-10 "scenes" (the last scene is the moral).
   Big emoji art + one or two simple sentences, read aloud. */
window.STORIES = [
  {
    id: 'crow',
    title: 'The Thirsty Crow',
    cover: '🐦‍⬛',
    scenes: [
      { art: '🐦‍⬛☀️', text: 'On a hot, sunny day, a little crow was very, very thirsty.' },
      { art: '🔍🌳', text: 'She flew here and there, looking everywhere for water.' },
      { art: '🏺', text: 'At last she found a tall pot with a little water at the bottom.' },
      { art: '🐦‍⬛🏺', text: 'But the water was too low. She could not reach it!' },
      { art: '🤔💡', text: 'The clever crow thought and thought... then she had an idea!' },
      { art: '🪨🪨', text: 'She picked up small stones, one by one.' },
      { art: '🏺💦', text: 'Plop! Plop! She dropped each stone into the pot.' },
      { art: '⬆️💧', text: 'Slowly, the water rose higher and higher.' },
      { art: '🐦‍⬛😋', text: 'Now she could drink. The happy crow drank every drop!' },
      { art: '🌟', text: 'Moral: Where there is a will, there is a way.' },
    ],
  },
  {
    id: 'tortoise',
    title: 'The Tortoise and the Hare',
    cover: '🐢',
    scenes: [
      { art: '🐇💨', text: 'A speedy hare loved to brag, "I am the fastest of all!"' },
      { art: '🐢🙂', text: 'A slow little tortoise said, "Let us have a race."' },
      { art: '🐇😂', text: 'The hare laughed. "You? Race me? This will be easy!"' },
      { art: '🏁🏃', text: 'Ready, set, GO! The hare zoomed far, far ahead.' },
      { art: '🐇😴🌳', text: 'So far ahead that he took a nap under a tree.' },
      { art: '🐢👣', text: 'The tortoise kept walking, step by step, never stopping.' },
      { art: '🐢➡️🐇', text: 'Slowly he passed the sleeping hare.' },
      { art: '🐇😱', text: 'The hare woke up and ran, but it was too late!' },
      { art: '🐢🏆', text: 'The tortoise crossed the finish line and won!' },
      { art: '🌟', text: 'Moral: Slow and steady wins the race.' },
    ],
  },
  {
    id: 'ant',
    title: 'The Ant and the Grasshopper',
    cover: '🐜',
    scenes: [
      { art: '☀️🌻', text: 'It was a warm summer. A grasshopper played and sang all day.' },
      { art: '🐜🌾', text: 'A busy ant worked hard, carrying food to her home.' },
      { art: '🦗🎶', text: '"Come play!" said the grasshopper. "Why work so hard?"' },
      { art: '🐜❄️', text: '"Winter is coming," said the ant. "We must be ready."' },
      { art: '🦗😴', text: 'But the grasshopper just laughed and kept playing.' },
      { art: '❄️🌨️', text: 'Soon, cold winter came. The fields were covered in snow.' },
      { art: '🦗🥶', text: 'The grasshopper was hungry and cold. There was no food!' },
      { art: '🐜🏠🍲', text: 'The kind ant had a warm home and plenty to eat.' },
      { art: '🐜🤝🦗', text: 'She shared her food, and the grasshopper learned his lesson.' },
      { art: '🌟', text: 'Moral: Work hard today, and you will be ready for tomorrow.' },
    ],
  },
  {
    id: 'lion',
    title: 'The Lion and the Mouse',
    cover: '🦁',
    scenes: [
      { art: '🦁😴', text: 'A big lion was fast asleep in the warm sun.' },
      { art: '🐭🏃', text: 'A tiny mouse ran across his nose and woke him up!' },
      { art: '🦁😾', text: 'The lion grabbed the little mouse with his huge paw.' },
      { art: '🐭🙏', text: '"Please let me go," squeaked the mouse. "One day I will help you!"' },
      { art: '🦁😄', text: 'The lion laughed, "How can YOU help ME?" But he let her go.' },
      { art: '🕸️🦁', text: 'Days later, the lion got caught in a hunter’s net.' },
      { art: '🦁😢', text: 'He roared and roared, but he could not get free.' },
      { art: '🐭👂', text: 'The little mouse heard him and came running.' },
      { art: '🐭✂️', text: 'She chewed the ropes until the lion was free!' },
      { art: '🌟', text: 'Moral: Even the smallest friend can be a big help.' },
    ],
  },
  {
    id: 'seed',
    title: 'The Little Seed',
    cover: '🌱',
    scenes: [
      { art: '🌰🤲', text: 'A little girl planted one tiny seed in the soft brown soil.' },
      { art: '💧☀️', text: 'Every day she gave it water and let it feel the sun.' },
      { art: '🌱👀', text: 'For many days, nothing happened. The seed stayed hidden.' },
      { art: '😟', text: '"Will it ever grow?" she wondered. But she did not give up.' },
      { art: '🌱✨', text: 'One morning, a tiny green sprout peeked out of the soil!' },
      { art: '🌿📈', text: 'Day by day, it grew taller and stronger.' },
      { art: '🌷🌼', text: 'Soon, beautiful flowers bloomed all around.' },
      { art: '🦋🐝', text: 'Butterflies and bees came to visit the lovely garden.' },
      { art: '😊🌻', text: 'The girl smiled. Her patience had grown something wonderful.' },
      { art: '🌟', text: 'Moral: Good things grow for those who are patient and kind.' },
    ],
  },
  {
    id: 'bear',
    title: 'The Two Friends and the Bear',
    cover: '🐻',
    scenes: [
      { art: '👬🌳', text: 'Two friends were walking through a big, green forest.' },
      { art: '🐻😨', text: 'Suddenly, a big bear came out from behind the trees!' },
      { art: '🏃🌳', text: 'One friend ran fast and climbed up a tall tree.' },
      { art: '🧍😰', text: 'The other friend did not know how to climb. He was scared.' },
      { art: '💡🛌', text: 'He remembered: bears do not touch those who lie very still.' },
      { art: '🧍⬇️', text: 'So he lay down on the ground and held his breath.' },
      { art: '🐻👃', text: 'The bear sniffed his ear... then walked away.' },
      { art: '🌳👀', text: 'The friend in the tree climbed down. "What did the bear say?"' },
      { art: '🗣️🤝', text: '"He said: a true friend never leaves you in trouble."' },
      { art: '🌟', text: 'Moral: A true friend stays with you, even in hard times.' },
    ],
  },
  {
    id: 'sun',
    title: 'The Sun and the Wind',
    cover: '🌞',
    scenes: [
      { art: '🌬️🌞', text: 'The Wind and the Sun argued about who was stronger.' },
      { art: '🚶🧥', text: 'They saw a man walking, wearing a warm coat.' },
      { art: '🌬️💪', text: '"Whoever makes him take off his coat wins!" said the Wind.' },
      { art: '🌬️🥶', text: 'The Wind blew hard and cold, whoosh, whoosh!' },
      { art: '🧥🤗', text: 'But the man only held his coat tighter and tighter.' },
      { art: '🌬️😮‍💨', text: 'The Wind blew and blew until he was all tired out.' },
      { art: '🌞😊', text: 'Then the Sun came out and shone warm and gentle.' },
      { art: '☀️😅', text: 'The man felt warm... so he took off his coat!' },
      { art: '🌞🏆', text: 'The gentle Sun had won.' },
      { art: '🌟', text: 'Moral: Kindness and gentleness are stronger than force.' },
    ],
  },
];
